name: imagenet
root: ${oc.env:DATA_ROOT,./data}/imagenet
num_classes: 1000
image_size: 224
num_workers: 4
batch_size: 128
mean: [0.485, 0.456, 0.406]  # ImageNet standard mean
std: [0.229, 0.224, 0.225]   # ImageNet standard std