name: experience_replay
memory_size: 200 # Total size of buffer
selection_strategy: random # Method to select examples from buffer
batch_size_memory: 32 # Num of examples sampled from buffer at each training iteration