name: class_incremental
num_tasks: 10  # Number of tasks to split the dataset into
shuffle_classes: true
random_seed: ${seed}

# Note: number of classes per task is auto calculated in the scenario_loader.py file