# Hydra base configuration file

defaults:
  - model: vit                       # Default foundation model
  - dataset: cifar100             # Primary dataset
  - continual_learning/scenario: class_incremental # CIL for Continual learning setting
  - continual_learning/method: replay/er           # Start with Experience Replay for CL
  - continual_learning/ood_detection: energy       # Energy-based OOD
  - training: default
  - logging: wandb
  - _self_

# General parameters
seed: 42 # random seed for reproducability
device: cuda # setting device to GPU for efficiency
num_workers: 4 # setting workers for the data loading efficieny
output_dir: ${hydra:runtime.output_dir}
shuffle_classes: true # shuffle classes for the incremental learning scenario
save_model: false # save the model after training

# Experiment settings
experiment:
  name: ${model.name}_${dataset.name}_${continual_learning.method.name}
  tags: [continual, foundation_model, ood]